### ISSUE TITLE
CI Flakiness on unit tests

### ISSUE THREAD

**Issue by briancoutinho** [facebookincubator/dynolog#118]
We see CI failing randomly on past few PRs. When the github action runs it just shows busy without any output.
The failures logs get truncated around the 'SimpleJsonClientTest' but not sure if this is a red herring.

Here is an example flow
https://github.com/facebookincubator/dynolog/actions/runs/4441365548/jobs/7796346665

**Comment by bigzachattack** [comment]
@briancoutinho I believe 'SimpleJsonClientTest' is the real thing.  I have re-run the CI workflow in the past and watch live output, if the workflow stalls it is after the test starts.
