### ISSUE TITLE
Cannot capture CPU mertics inside docker container.

### ISSUE THREAD

**Issue by stricklandye** [facebookincubator/dynolog#183]
Hi there. Why can't dynolog capture the CPU metrics and  there is no log in `/var/log/dynolog.log`. Is there something wrong with the way I use it？
## How to Reproduce
1. Use the [dynolog_hta.dockerfile](https://github.com/facebookincubator/dynolog/blob/main/dynolog_hta.dockerfile) build image
2. Use following command to run a contanier:
```shell
docker run -ti -v /usr/src:/usr/src:ro \
        -v /lib/modules/:/lib/modules:ro \
        -v /sys/kernel/debug/:/sys/kernel/debug:rw \
        --net=host --pid=host --privileged \
        dynolog:v0.1 \
        bash  
```
3. Inside the container, start dynolog. **But nothing about CPU metrics were recorded and the log file didn't exist either :(**.
```
/workspace# dynolog  --enable-perf-monitor
I20231107 12:06:08.049125 968085 Main.cpp:151] Starting dynolog, version = 0.2.2, build git-hash = d70fccd
I20231107 12:06:08.049226 968085 SimpleJsonServer.cpp:82] Listening to connections on port 1778
I20231107 12:06:08.049235 968085 SimpleJsonServer.cpp:229] Launching RPC thread
I20231107 12:06:08.049328 968088 SimpleJsonServer.cpp:207] Waiting for connection.
I20231107 12:06:08.049425 968086 Main.cpp:82] Running kernel monitor loop : interval = 60 s.
I20231107 12:06:08.061357 968087 Main.cpp:106] Running perf monitor loop : interval = 60 s.
/workspace# ls /var/log
alternatives.log  apt  bootstrap.log  btmp  dpkg.log  faillog  lastlog  wtmp
```
By the way, I have also tried to run dynolog in host but dynolog is not compatible with the openssl that already installed(openssl 3.0.2). It seems that dynolog requires openssl 1.1.1, however it  will no longer be maintained soon (according to [openssl doc](https://www.openssl.org/source/)). So I think it is better to use the newer openSSL.

**Comment by briancoutinho** [comment]
Hi @stricklandye  for the docker/HTA demo ah dynolog is not configured to emit the metrics. 
Try adding these flags and you can also configure the logging/measurement interval
```
dynolog  --enable-perf-monitor --use_JSON   --kernel_monitor_reporting_interval_s 10 --perf_monitor_reporting_interval_s 10
```
Let us know if this works.
Flag reference = https://github.com/facebookincubator/dynolog/blob/main/dynolog/src/Main.cpp#L44

PS: There is an early stage support for Prometheus too, see the test plan in the PR below for instructions, you may need to merge the docker file commands from this test plan with yours above.
https://github.com/facebookincubator/dynolog/pull/181

PS: open ssl is probably getting used by a dependency we use ~cpr, will get back on it.

**Comment by stricklandye** [comment]
Sorry for not reply in time,  using `--use_JSON` works well. I will close this issue.

**Comment by stricklandye** [comment]
@briancoutinho  Hi, I have also several questions:
1. the doc says the `KINETO_USE_DAEMON =1` and `dynolog --enable_ipc_monitor ` is required to trace GPU. What is the right way to trace GPU inside a Kubernetes Cluster? If running dynolog as daemon service, it seems cannot trace AI program runs inside a container and It's not feasible to bundle dynolog with every containter images.
2. Is the performance overhead of dynolog GPU trace high?

**Comment by stricklandye** [comment]
I see. Have a great time :D
