### ISSUE TITLE
Pytorch example does not work without GPU

### ISSUE THREAD

**Issue by cameron-martin** [facebookincubator/dynolog#208]
After setting up dynolog to `--enable_ipc_monitor`, I have tried running the example (but changing the device to CPU) like so:

```sh
KINETO_USE_DAEMON=1 python scripts/pytorch/linear_model_example.py
```

Then if I run `dyno gputrace`, I get the following:

```
No processes were matched, please check --job-id or --pids flags
```

If I wrap the example in a profiler, then I do get matched processes. However, I thought the point what that it required no code modifications?

```py
with profile(activities=[ProfilerActivity.CPU], record_shapes=True) as prof:
```

This does create a trace, but it doesn't contain much useful info. See attached file.

[dynolog.json](https://github.com/facebookincubator/dynolog/files/13918204/dynolog.json)

What am I doing wrong?

**Comment by jj10306** [comment]
@cameron-martin 
> but changing the device to CPU
`dyno gputrace` only supports tracing Pytorch executing **on GPU**

cc: @briancoutinho to confirm

**Comment by cameron-martin** [comment]
Why does it require a GPU if both dynolog and kineto claim to support CPU profiling?

**Comment by briancoutinho** [comment]
@cameron-martin Yes, actually dynolog and kineto support CPU-only profiling too. Tbh we didn't test the on-demand tracing flow on a pure CPU version of PyTorch. I'll give it a try with a latest release of cpu torch, but please do share the versions you used as well.


You are right that [libkineto_init()](https://github.com/pytorch/kineto/blob/eb56921f8cf6f4d14c16c45fe7586d5a6dccaf9e/libkineto/src/init.cpp#L109-L120) is where the actual registry happens with dynolog. The `libkineto_init()` is invoked in multiple places.
1. During strartup in profiler registry [here](https://github.com/pytorch/pytorch/blob/main/torch/csrc/profiler/kineto_client_interface.cpp#L72-L80).
2. Lazily called during first usage of PyTorch profiler [here](https://github.com/pytorch/pytorch/blob/main/torch/csrc/profiler/kineto_shim.cpp#L206-L212).

Actually we wanted (1) to always be invoked but i think some define is probably compiling it out like this [`ENABLE_GLOBAL_OBSERVER` thing](https://github.com/pytorch/pytorch/blob/main/torch/csrc/profiler/kineto_client_interface.cpp#L6-L9). 
Any chance you are using an Apple system or PyTorch edge?

```
#if defined(__APPLE__) || defined(EDGE_PROFILER_USE_KINETO)
#define ENABLE_GLOBAL_OBSERVER (0)
#else
```

**Comment by cameron-martin** [comment]
I'm using:

* PyTorch 2.1.2
* Linux
* Dynolog 0.3.0 (this is the latest release that has deb packages)

I also compiled HEAD of dynolog and tested but still get the same results.

**Comment by briancoutinho** [comment]
@cameron-martin thanks for the info, I think the issue is in the PyTorch side as in libkineto is not getting initialized. I'll try to repro the CPU only setup and get back to you.

**Comment by briancoutinho** [comment]
Working on two WIP fixes
https://github.com/pytorch/kineto/pull/861 (have to land this first)
https://github.com/pytorch/pytorch/pull/118320

**Comment by briancoutinho** [comment]
Ok all fixes are in https://github.com/pytorch/pytorch/pull/118320 :)
Can you try out PyTorch nightly build to see if this works, I tried it out for developing the PR. Let me know..

**Comment by cameron-martin** [comment]
Just tested this with nightly torch and it works great, thanks!
