### ISSUE TITLE
Kineto/dynolog IPC + kubernetes

### ISSUE THREAD

**Issue by jon-chuang** [facebookincubator/dynolog#241]
Hey guys awesome work.

Quick question about k8s compat:

If the kineto instrumented processes are running in K8s containers, are you guys aware if enabling host IPC, and running dynolog sidecar container is sufficient to facilitate the on-demand profiling use case?

Seems like running into k8s compat would be quite likely on production path for you guys so any details here would be really helpful.

Thanks!

**Comment by briancoutinho** [comment]
@jon-chuang  sorry we missed this, if you can have the dynolog process run within the container and then have dynolog's port exported I think it should work.

There is an example docker file here that could be helpful
https://pytorch.org/blog/automated-trace-collection/

**Comment by rtanase** [comment]
+ 1

**Comment by briancoutinho** [comment]
Let me know if this issue can be closed 👍
