### ISSUE TITLE
Upload release packages for v0.3.2

### ISSUE THREAD

**Issue by abatilo** [facebookincubator/dynolog#257]
I noticed that there aren't any attached release packages for v0.3.1 or v0.3.2. Could someone create and upload those, please? Thank you

**Comment by briancoutinho** [comment]
@abatilo sorry about the delay, can you share what type of package you will need, deb or rpm?

**Comment by abatilo** [comment]
deb would be great!

**Comment by briancoutinho** [comment]
@abatilo  please check the release page :)
