### ISSUE TITLE
GPL-3.0 license detected in a third_party file

### ISSUE THREAD

**Issue by jamesjordan522** [facebookincubator/dynolog#278]
This issue was originally reported here: https://github.com/pytorch/pytorch/issues/132151

dynolog is currently distributed under the MIT license, however a GPL-v3 file is part of the third party tool 'cpr', see `third_party/cpr/test/LICENSE`

Can this issue be resolved?

**Comment by jamesjordan522** [comment]
Further research showed, that dynolog uses
```
add_subdirectory(third_party/cpr)
target_link_libraries(dynolog_lib PUBLIC cpr::cpr)
```
in its `CMakeLists.txt`.

In cpr's `CMakeLists.txt`  the `CPR_BUILD_TESTS` flag is set to `OFF` by default.

Consequently, it seems like building dynolog is not affected by this GPL license. Can anyone confirm this?

**Comment by briancoutinho** [comment]
@jamesjordan522  thank you so much for checking the details. I can confirm we do not run tests for CPR in our build flow.
If required I can explicitly add it in the CMakeLists.txt as well.

https://github.com/facebookincubator/dynolog/blob/main/CMakeLists.txt#L54-L58

Closing this issue for now but please feel free to re-open.
