### ISSUE TITLE
no processes were matched

### ISSUE THREAD

**Issue by zuquan-song** [facebookincubator/dynolog#280]
When I try to use dynolog, I received a no processes were matched

> (venv) song@DESKTOP-PTNOBH3:/mnt/d/code/torch_playground$ /usr/local/bin/dyno gputrace --log-file trace.log --pids 80295
Kineto config = 
ACTIVITIES_LOG_FILE=trace.log\nPROFILE_START_TIME=0\nACTIVITIES_DURATION_MSECS=500
response length = 133
response = {"activityProfilersBusy":0,"activityProfilersTriggered":[],"eventProfilersBusy":0,"eventProfilersTriggered":[],"processesMatched":[]}
No processes were matched, please check --job-id or --pids flags

Here is how I setup the my training

terminal 1:
> (venv) song@DESKTOP-PTNOBH3:/mnt/d/package$ /usr/local/bin/dynolog 
I20240810 14:23:21.223451 51761 Main.cpp:151] Starting dynolog, version = 0.2.1, build git-hash = 
I20240810 14:23:21.223624 51761 SimpleJsonServer.cpp:82] Listening to connections on port 1778
I20240810 14:23:21.223651 51761 SimpleJsonServer.cpp:229] Launching RPC thread
I20240810 14:23:21.223729 51763 SimpleJsonServer.cpp:207] Waiting for connection.
I20240810 14:23:21.223841 51762 Main.cpp:82] Running kernel monitor loop : interval = 60 s.
I20240810 14:28:42.334342 51763 SimpleJsonServer.cpp:118] Received connection from ::ffff:127.0.0.1
I20240810 14:28:42.334363 51763 SimpleJsonServer.cpp:214] RPC message received = 
{
    "fn": "setKinetOnDemandRequest",
    "config": "ACTIVITIES_LOG_FILE=output.log\nPROFILE_START_TIME=0\nACTIVITIES_DURATION_MSECS=500",
    "job_id": 0,
    "pids": [0],
    "process_limit": 3
}

terminal 2:
> export KINETO_USE_DAEMON=1
export  KINETO_DAEMON_INIT_DELAY_S=3

running training process
> python xxx.py

And the following is the output for training processes, I listed some key logs that might help troubleshooting
> INFO:2024-08-10 15:33:26 85585:85666 init.cpp:131] Registering daemon config loader, cpuOnly =  0
ERROR: External init callback must run in same thread as registerClient (1784673856 != 2058534912)
...
ERROR:2024-08-10 15:35:43 85585:86150 IpcFabricConfigClient.cpp:175] Failed to send config type=3 to dyno: IPC sync_send fail  

terminal 3:
> (venv) song@DESKTOP-PTNOBH3:/mnt/d/code/torch_playground$ /usr/local/bin/dyno gputrace --log-file trace.log --pids 80295
Kineto config = 
ACTIVITIES_LOG_FILE=trace.log\nPROFILE_START_TIME=0\nACTIVITIES_DURATION_MSECS=500
response length = 133
response = {"activityProfilersBusy":0,"activityProfilersTriggered":[],"eventProfilersBusy":0,"eventProfilersTriggered":[],"processesMatched":[]}
No processes were matched, please check --job-id or --pids flags                             

Environment:
> 1. python 3.10
> 2.  torch 2.4
> 3.  cuda 12.6
> 4.  WSL 2
> 5.  RTX 4090

**Comment by zuquan-song** [comment]
It will be SUPER helpful if someone helps

**Comment by briancoutinho** [comment]
@zuquan-song I think you are missing enable ipc monitor flag in dynolog `dynolog --enable_ipc_monitor`

So the PyTorch process is not able to talk to dynolog over ipc 
> ERROR:2024-08-10 15:35:43 85585:86150 IpcFabricConfigClient.cpp:175] Failed to send config type=3 to dyno: IPC sync_send fail

Without this registry dynolog will think there are no PyTorch processes

**Comment by zuquan-song** [comment]
Thanks! It works

**Comment by zuquan-song** [comment]
> @zuquan-song I think you are missing enable ipc monitor flag in dynolog `dynolog --enable_ipc_monitor`
> 
> So the PyTorch process is not able to talk to dynolog over ipc
> 
> > ERROR:2024-08-10 15:35:43 85585:86150 IpcFabricConfigClient.cpp:175] Failed to send config type=3 to dyno: IPC sync_send fail
> 
> Without this registry dynolog will think there are no PyTorch processes

Thanks! It works!
